---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
