apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: tenant1
spec:
  releaseName: wordpress
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 12.0.0
  values:
    wordpressUsername: user
    wordpressPassword: password
    mariadb.auth.rootPassword: secretpassword
